
CREATE TABLE CARS
(
  MODEL                VARCHAR(50) NULL     COMMENT '자동차이름',
  YEAR_OF_PRODUCTION   INTEGER     NULL     COMMENT '연식',
  UNIQUE_ID            VARCHAR(50) NOT NULL COMMENT '식별자',
  CARS_COMPANY_CODE_ID VARCHAR(50) NOT NULL COMMENT '회사이름_ID',
  PRIMARY KEY (UNIQUE_ID)
) COMMENT '자동차';

CREATE TABLE CARS_COMPANY_CODE
(
  COMPANY              VARCHAR(50) NULL     COMMENT '회사이름',
  CARS_COMPANY_CODE_ID VARCHAR(50) NOT NULL COMMENT '회사이름_ID',
  PRIMARY KEY (CARS_COMPANY_CODE_ID)
) COMMENT '회사이름_코드';

CREATE TABLE CARS_OPTIONS
(
  OPTIONS         VARCHAR(50) NULL     COMMENT '옵션',
  CARS_OPTIONS_ID VARCHAR(50) NOT NULL COMMENT '자동차_옵션_ID',
  UNIQUE_ID       VARCHAR(50) NOT NULL COMMENT '식별자'
) COMMENT '자동차_옵션';

CREATE TABLE CARS_OPTIONS_CODE
(
  OPTIONS         VARCHAR(50) NULL     COMMENT '옵션',
  CARS_OPTIONS_ID VARCHAR(50) NOT NULL COMMENT '자동차_옵션_ID',
  PRIMARY KEY (CARS_OPTIONS_ID)
) COMMENT '자동차_옵션_코드';

ALTER TABLE CARS
  ADD CONSTRAINT FK_CARS_COMPANY_CODE_TO_CARS
    FOREIGN KEY (CARS_COMPANY_CODE_ID)
    REFERENCES CARS_COMPANY_CODE (CARS_COMPANY_CODE_ID);

ALTER TABLE CARS_OPTIONS
  ADD CONSTRAINT FK_CARS_OPTIONS_CODE_TO_CARS_OPTIONS
    FOREIGN KEY (CARS_OPTIONS_ID)
    REFERENCES CARS_OPTIONS_CODE (CARS_OPTIONS_ID);

ALTER TABLE CARS_OPTIONS
  ADD CONSTRAINT FK_CARS_TO_CARS_OPTIONS
    FOREIGN KEY (UNIQUE_ID)
    REFERENCES CARS (UNIQUE_ID);
