
CREATE TABLE BLOOD_PRESSURE_GLUCOSE_LEVEL
(
  BLOOD_PRESSURE       INTEGER     NOT NULL COMMENT '혈압(mmHg)',
  BLOOD_ GLUCOSE_LEVEL INTEGER     NOT NULL COMMENT '혈당(mg/dL)',
  ID                   VARCHAR(50) NOT NULL COMMENT '식별자'
) COMMENT '혈압(mmHg), 혈당(mg/dL)';

CREATE TABLE HW
(
  ID     VARCHAR(50) NOT NULL COMMENT '식별자',
  HEIGHT INTEGER     NOT NULL COMMENT '키(cm)',
  WEIGHT INTEGER     NOT NULL COMMENT '체중(kg)'
) COMMENT '키(cm), 체중(kg)';

CREATE TABLE LIST_OF_REEXAMINATIONS
(
  LIST_OF_REEXAMINATIONS      VARCHAR(50) NOT NULL COMMENT '재검진항목',
  ID                          VARCHAR(50) NOT NULL COMMENT '식별자',
  LIST_OF_REEXAMINATIONS_CODE VARCHAR(50) NOT NULL COMMENT '재검진항목_코드'
) COMMENT '재검진항목';

CREATE TABLE LIST_OF_REEXAMINATIONS_CODE
(
  LIST_OF_REEXAMINATIONS_CODE VARCHAR(50) NOT NULL COMMENT '재검진항목_코드',
  LIST_OF_REEXAMINATIONS      VARCHAR(50) NOT NULL COMMENT '재검진항목',
  PRIMARY KEY (LIST_OF_REEXAMINATIONS_CODE)
) COMMENT '재검진항목_코드';

CREATE TABLE MAINTANANCE_PLAN
(
  MAINTANANCE_PLAN    VARCHAR(50) NOT NULL COMMENT '유지방안',
  ID                  VARCHAR(50) NOT NULL COMMENT '식별자',
  MAINTANCE_PLAN_CODE VARCHAR(50) NOT NULL COMMENT '유지방안_코드'
) COMMENT '유지방안';

CREATE TABLE MAINTANCE_PLAN_CODE
(
  MAINTANCE_PLAN      VARCHAR(50) NOT NULL,
  MAINTANCE_PLAN_CODE VARCHAR(50) NOT NULL COMMENT '유지방안_코드',
  PRIMARY KEY (MAINTANCE_PLAN_CODE)
) COMMENT '유지방안_코드';

CREATE TABLE MEDICAL_CHECKUP
(
  ID           VARCHAR(50) NOT NULL COMMENT '식별자',
  NAME         VARCHAR(50) NOT NULL COMMENT '이름',
  AGE          INTEGER     NOT NULL COMMENT '나이',
  SEX_CODE     VARCHAR(50) NOT NULL COMMENT '성별_코드',
  RESULTS_CODE VARCHAR(50) NOT NULL COMMENT '검진결과_코드',
  PRIMARY KEY (ID)
) COMMENT '건강검진';

CREATE TABLE RESULTS_CODE
(
  RESULTS      VARCHAR(50) NOT NULL COMMENT '검진결과',
  RESULTS_CODE VARCHAR(50) NOT NULL COMMENT '검진결과_코드',
  PRIMARY KEY (RESULTS_CODE)
) COMMENT '검진결과_코드';

CREATE TABLE SEX_CODE
(
  SEX      VARCHAR(50) NOT NULL COMMENT '성별',
  SEX_CODE VARCHAR(50) NOT NULL COMMENT '성별_코드',
  PRIMARY KEY (SEX_CODE)
) COMMENT '성별_코드';

ALTER TABLE BLOOD_PRESSURE_GLUCOSE_LEVEL
  ADD CONSTRAINT FK_MEDICAL_CHECKUP_TO_BLOOD_PRESSURE_GLUCOSE_LEVEL
    FOREIGN KEY (ID)
    REFERENCES MEDICAL_CHECKUP (ID);

ALTER TABLE LIST_OF_REEXAMINATIONS
  ADD CONSTRAINT FK_MEDICAL_CHECKUP_TO_LIST_OF_REEXAMINATIONS
    FOREIGN KEY (ID)
    REFERENCES MEDICAL_CHECKUP (ID);

ALTER TABLE LIST_OF_REEXAMINATIONS
  ADD CONSTRAINT FK_LIST_OF_REEXAMINATIONS_CODE_TO_LIST_OF_REEXAMINATIONS
    FOREIGN KEY (LIST_OF_REEXAMINATIONS_CODE)
    REFERENCES LIST_OF_REEXAMINATIONS_CODE (LIST_OF_REEXAMINATIONS_CODE);

ALTER TABLE MAINTANANCE_PLAN
  ADD CONSTRAINT FK_MEDICAL_CHECKUP_TO_MAINTANANCE_PLAN
    FOREIGN KEY (ID)
    REFERENCES MEDICAL_CHECKUP (ID);

ALTER TABLE HW
  ADD CONSTRAINT FK_MEDICAL_CHECKUP_TO_HW
    FOREIGN KEY (ID)
    REFERENCES MEDICAL_CHECKUP (ID);

ALTER TABLE MEDICAL_CHECKUP
  ADD CONSTRAINT FK_SEX_CODE_TO_MEDICAL_CHECKUP
    FOREIGN KEY (SEX_CODE)
    REFERENCES SEX_CODE (SEX_CODE);

ALTER TABLE MAINTANANCE_PLAN
  ADD CONSTRAINT FK_MAINTANCE_PLAN_CODE_TO_MAINTANANCE_PLAN
    FOREIGN KEY (MAINTANCE_PLAN_CODE)
    REFERENCES MAINTANCE_PLAN_CODE (MAINTANCE_PLAN_CODE);

ALTER TABLE MEDICAL_CHECKUP
  ADD CONSTRAINT FK_RESULTS_CODE_TO_MEDICAL_CHECKUP
    FOREIGN KEY (RESULTS_CODE)
    REFERENCES RESULTS_CODE (RESULTS_CODE);
